#!/bin/python3

"""
This script will change focus in tiling window and make the window on top of stack if it is floating.
Uses hyprctl.
"""

import json
import subprocess
import sys

dir = sys.argv[1]

if dir not in [ "l", "r", "u", "d" ]:
    sys.exit(1)

subprocess.run(
    f"hyprctl dispatcher movefocus {dir}",
    shell=True,
    capture_output=True,
    check=True,
    text=True,
)

command = subprocess.run(
    "hyprctl activewindow -j", shell=True, capture_output=True, check=True, text=True
)

data = json.loads(command.stdout)
if data["floating"]:
    subprocess.run(
        f"hyprctl dispatcher bringactivetotop none",
        shell=True,
        capture_output=True,
        check=True,
        text=True,
    )
